FROM rust:1.76 AS builder
WORKDIR /app
COPY src/rust .
ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL
RUN cargo build --release

FROM debian:bookworm-slim
COPY --from=builder /app/target/release/agrodash-api /app/agrodash-api
CMD ["/app/agrodash-api"]