FROM rust:bookworm AS builder
WORKDIR /app
COPY src/rust .
ENV SQLX_OFFLINE=true
RUN cargo build --release

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y libssl-dev ca-certificates && rm -rf /var/lib/apt/lists/*
COPY --from=builder /app/target/release/agrodash-api /app/agrodash-api
CMD ["/app/agrodash-api"]